# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
twitter_insights_username: "258e41cf-7697-48b2-a08c-f2c6066019a2"
twitter_insights_password: "lBXODlkt1C"
twitter_insights_host: "cdeservice.mybluemix.net"
twitter_insights_port: "443"
twitter_insights_url: "https://258e41cf-7697-48b2-a08c-f2c6066019a2:lBXODlkt1C@cdeservice.mybluemix.net"
